name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build application
      run: npm run build
    
    - name: Deploy to Render
      run: |
        echo "Starting Render deployment..."
        echo "Service ID: ${{ secrets.RENDER_SERVICE_ID }}"
        
        if [ -z "${{ secrets.RENDER_SERVICE_ID }}" ]; then
          echo "Error: RENDER_SERVICE_ID is not set"
          exit 1
        fi
        
        if [ -z "${{ secrets.RENDER_API_KEY }}" ]; then
          echo "Error: RENDER_API_KEY is not set"
          exit 1
        fi
        
        DEPLOY_URL="https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"
        echo "Deploy URL: $DEPLOY_URL"
        
        curl -v -X POST "$DEPLOY_URL" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": "do"}' \
          --fail 